apiVersion: apps/v1
kind: Deployment

metadata:
  name: secure-ci-node
  labels:
    app: secure-ci-node

spec:
  replicas: 2

  selector:
    matchLabels:
      app: secure-ci-node

  template:
    metadata:
      labels:
        app: secure-ci-node

    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: secure-ci-node
          image: ghcr.io/einhorny2020/secure-ci-node:1.0.1

          ports:
            - containerPort: 3000

          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true

            capabilities:
              drop:
                - ALL

          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"
