apiVersion: apps/v1
kind: Deployment

metadata:
  name: secure-ci-node
  labels:
    app: secure-ci-node

spec:
  replicas: 1

  selector:
    matchLabels:
      app: secure-ci-node

  template:
    metadata:
      labels:
        app: secure-ci-node

    spec:
      hostNetwork: true

      containers:
        - name: secure-ci-node
          image: ghcr.io/einhorny2020/secure-ci-node:latest

          ports:
            - containerPort: 3000

          securityContext:
            privileged: true
            runAsUser: 0
            allowPrivilegeEscalation: true
