name: Pipeline DevSecOps

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: devsecops-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

###########################################################
# TESTS
###########################################################

  test:

    name: Tests applicatifs

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Installer les dépendances
        run: npm ci

      - name: Exécuter les tests
        run: npm test

###########################################################
# Détection des secrets
###########################################################
  secret_scan:

    name: Détection des secrets

    needs:

        test

    runs-on: ubuntu-latest

    permissions:

        contents: read

    steps:

    - uses: actions/checkout@v4

    - name: Secret Scan

      uses: aquasecurity/trivy-action@0.28.0

      with:

          scan-type: fs

          scan-ref: .

          scanners: secret

          exit-code: '1'


###########################################################
# ANALYSE SCA
###########################################################

  sca:

    name: Analyse SCA avec Trivy

    needs:
      - test

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Analyse des dépendances
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: "1"
          format: table

###########################################################
# BUILD
###########################################################

  build:

    name: Construction Docker

    needs:
      - test
      - sca

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Construire l'image Docker
        run: |
          docker build \
          -t secure-ci-node:${{ github.sha }} \
          .

###########################################################
# PUBLICATION
###########################################################

  publish:

    name: Publication GHCR

    needs:
      - test
      - sca
      - build

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Connexion GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construction et publication
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/secure-ci-node:latest
            ghcr.io/${{ github.repository_owner }}/secure-ci-node:${{ github.sha }}